# Generated by Django 5.2.3 on 2025-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concert', 'Concert'), ('Picnic', 'Picnic'), ('Party', 'Party'), ('Workshop', 'Workshop'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
